# Generated by Django 3.0 on 2020-12-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tabs',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
