# Generated by Django 3.0 on 2020-12-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0002_auto_20201219_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.AddField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
